steps:
  # Build & push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/image-upload-gcp-project/cloud-native-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/image-upload-gcp-project/cloud-native-app']

  # Deploy BLUE version (50% traffic)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cloud-native-app'
      - '--image=gcr.io/image-upload-gcp-project/cloud-native-app'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-env-vars=BACKGROUND_COLOR=blue'
      - '--revision-suffix=blue'

  # Deploy GREEN version (0% traffic initially)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cloud-native-app'
      - '--image=gcr.io/image-upload-gcp-project/cloud-native-app'
      - '--region=us-central1'
      - '--platform=managed'
      - '--update-env-vars=BACKGROUND_COLOR=green'
      - '--revision-suffix=green'
      - '--no-traffic'

  # Split traffic 50/50
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'cloud-native-app'
      - '--region=us-central1'
      - '--to-revisions=cloud-native-app-blue=50,cloud-native-app-green=50'
